# Generated by Django 3.0.8 on 2020-07-16 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0003_auto_20200717_0214'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
