# Generated by Django 3.0.8 on 2020-07-20 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0004_auto_20200717_0215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='type',
            field=models.TextField(choices=[('S', 'Student'), ('A', 'Academic Mentor'), ('I', 'Industry Mentor'), ('Z', 'Organization'), ('O', 'Others')]),
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('link', models.TextField(blank=True, null=True)),
                ('skills', models.ManyToManyField(blank=True, to='person.Skill')),
            ],
        ),
    ]
