# Generated by Django 3.0.8 on 2020-07-20 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0005_auto_20200720_2233'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForumSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('desc', models.TextField()),
                ('order', models.PositiveIntegerField()),
                ('isDeleted', models.BooleanField()),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('icon', models.ImageField(default='images/avatar.jpg', upload_to='images/')),
            ],
        ),
        migrations.RenameField(
            model_name='post',
            old_name='isOriginal',
            new_name='isDeleted',
        ),
        migrations.RenameField(
            model_name='reply',
            old_name='isOriginal',
            new_name='isDeleted',
        ),
        migrations.AddField(
            model_name='post',
            name='markdown',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reply',
            name='markdown',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='forumSection',
            field=models.ManyToManyField(blank=True, related_name='ManagesForumSection', to='person.ForumSection'),
        ),
        migrations.CreateModel(
            name='ForumCategory',
            fields=[
                ('forumsection_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='person.ForumSection')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='BelongsForumSection', to='person.ForumSection')),
            ],
            bases=('person.forumsection',),
        ),
        migrations.AddField(
            model_name='person',
            name='forumCategory',
            field=models.ManyToManyField(blank=True, related_name='ManagesForumCategory', to='person.ForumCategory'),
        ),
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='person.ForumCategory'),
        ),
    ]
