# Generated by Django 3.0.8 on 2020-07-20 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0006_auto_20200720_2323'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='forumcategory',
            options={'verbose_name_plural': 'Forum Categories'},
        ),
    ]
