# Generated by Django 3.0.8 on 2020-07-23 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0008_auto_20200723_2032'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='forumCategory',
        ),
        migrations.RemoveField(
            model_name='person',
            name='forumSection',
        ),
    ]
