# Generated by Django 3.0.8 on 2020-07-26 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0009_auto_20200723_2231'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='skills',
            field=models.ManyToManyField(blank=True, to='person.Skill'),
        ),
    ]
