# Generated by Django 3.0.8 on 2020-07-27 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0012_auto_20200728_0506'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='code',
        ),
    ]
