# Generated by Django 3.0.8 on 2020-07-28 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0013_remove_course_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='avatar',
            field=models.ImageField(blank=True, default='images/avatar.jpg', null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='person',
            name='desc',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='location',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='type',
            field=models.TextField(blank=True, choices=[('S', 'Student'), ('A', 'Academic Mentor'), ('I', 'Industry Mentor'), ('Z', 'Organization'), ('O', 'Others')], null=True),
        ),
    ]
