# Generated by Django 3.0.8 on 2020-08-02 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0014_auto_20200728_2104'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='resume/'),
        ),
    ]
