# Generated by Django 3.0.8 on 2020-08-08 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0016_auto_20200803_2323'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='company_name',
            field=models.TextField(default='NULL'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='opportunity',
            name='location',
            field=models.TextField(default='NULL'),
            preserve_default=False,
        ),
    ]
