# Generated by Django 3.0.8 on 2020-08-11 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0020_auto_20200811_1708'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meeting',
            options={'ordering': ('time',)},
        ),
        migrations.AlterField(
            model_name='person',
            name='resume',
            field=models.FileField(blank=True, default='resume/blank.pdf', null=True, upload_to='resume/'),
        ),
    ]
