# Generated by Django 3.0.8 on 2020-08-11 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0021_auto_20200812_0043'),
        ('person', '0021_auto_20200812_0052'),
    ]

    operations = [
    ]
