# Generated by Django 3.0.8 on 2020-08-12 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0022_merge_20200812_0150'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forumcategory',
            name='section',
        ),
        migrations.DeleteModel(
            name='ForumSection',
        ),
    ]
